# Generated by Django 5.0.7 on 2024-07-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_delete_allowedmac_allowedip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='root_password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='root_user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='status',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
