# Generated by Django 5.0.7 on 2024-07-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_database_root_password_database_root_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='db_type',
            field=models.CharField(choices=[('sqlite3', 'SQLite'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('oracle', 'Oracle')], default='sqlite3', max_length=20),
        ),
    ]
