# Generated by Django 5.0.7 on 2024-07-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0006_database_db_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='status',
            field=models.CharField(choices=[('Connected', 'Connected'), ('Disconnected', 'Disconnected')], default='Disconnected', max_length=20),
        ),
    ]
