# Generated by Django 5.0.7 on 2024-07-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0007_alter_database_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='root_password',
        ),
        migrations.RemoveField(
            model_name='database',
            name='root_user',
        ),
        migrations.AlterField(
            model_name='database',
            name='db_type',
            field=models.CharField(choices=[('sqlite3', 'SQLite3'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('oracle', 'Oracle')], max_length=10),
        ),
        migrations.AlterField(
            model_name='database',
            name='host',
            field=models.CharField(default='localhost', max_length=100),
        ),
        migrations.AlterField(
            model_name='database',
            name='port',
            field=models.CharField(default='', max_length=5),
        ),
    ]
