# Generated by Django 5.0.7 on 2024-07-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0009_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_type',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('INSERT', 'INSERT'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('DDL', 'DDL')], default='SELECT', max_length=6),
            preserve_default=False,
        ),
    ]
