# Generated by Django 5.0.7 on 2024-07-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0011_rename_can_ddl_permissiongroup_can_alter_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='is_committed',
            field=models.BooleanField(default=False),
        ),
    ]
