# Generated by Django 5.0.7 on 2024-07-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0012_query_is_committed'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongroup',
            name='query_examples',
            field=models.TextField(blank=True, null=True),
        ),
    ]
