# Generated by Django 5.0.7 on 2024-07-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0017_permission_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissiongroup',
            name='users',
        ),
        migrations.AlterField(
            model_name='query',
            name='query_type',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('INSERT', 'INSERT'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE'), ('DDL', 'DDL'), ('ENCRYPT', 'ENCRYPT'), ('DECRYPT', 'DECRYPT')], max_length=8),
        ),
    ]
