# Generated by Django 5.0.7 on 2024-07-15 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0018_remove_permissiongroup_users_alter_query_query_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allowedip',
            options={'verbose_name': '허용 IP', 'verbose_name_plural': '허용 IP'},
        ),
        migrations.AlterModelOptions(
            name='permissiongroup',
            options={'verbose_name': '권한 그룹', 'verbose_name_plural': '권한 그룹'},
        ),
        migrations.AlterModelOptions(
            name='query',
            options={'verbose_name': '쿼리 수행 로그', 'verbose_name_plural': '쿼리 수행 로그'},
        ),
        migrations.AlterModelOptions(
            name='userbehavior',
            options={'verbose_name': '로그인 관련 로그', 'verbose_name_plural': '로그인 관련 로그'},
        ),
        migrations.AlterField(
            model_name='database',
            name='db_type',
            field=models.CharField(choices=[('sqlite3', 'SQLite3'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('oracle', 'Oracle')], max_length=10, verbose_name='DB 타입'),
        ),
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='DB이름'),
        ),
        migrations.AlterField(
            model_name='database',
            name='password',
            field=models.CharField(max_length=100, verbose_name='DB비밀번호'),
        ),
        migrations.AlterField(
            model_name='database',
            name='user',
            field=models.CharField(max_length=100, verbose_name='DB계정명'),
        ),
    ]
