# Generated by Django 5.0.7 on 2024-07-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0019_alter_allowedip_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='db_type',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('pgsql', 'PostgreSQL')], max_length=10, verbose_name='DB 타입'),
        ),
    ]
