# Generated by Django 5.0.7 on 2024-07-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0020_alter_database_db_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='db_type',
            field=models.CharField(choices=[('sqlite3', 'SQLite3'), ('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('oracle', 'Oracle')], max_length=10, verbose_name='DB 타입'),
        ),
    ]
