# Generated by Django 5.0.7 on 2024-07-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0021_alter_database_db_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('object_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
