# Generated by Django 5.0.7 on 2024-07-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0022_databaseobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('user_host', models.CharField(max_length=255)),
                ('query_time', models.FloatField()),
                ('lock_time', models.FloatField()),
                ('rows_sent', models.IntegerField()),
                ('rows_examined', models.IntegerField()),
                ('db', models.CharField(max_length=255)),
                ('last_insert_id', models.IntegerField()),
                ('insert_id', models.IntegerField()),
                ('server_id', models.IntegerField()),
                ('sql_text', models.TextField()),
            ],
        ),
    ]
