# Generated by Django 5.0.7 on 2024-07-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0023_remotelog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remotelog',
            old_name='sql_text',
            new_name='argument',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='db',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='insert_id',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='last_insert_id',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='lock_time',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='query_time',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='rows_examined',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='rows_sent',
        ),
        migrations.RemoveField(
            model_name='remotelog',
            name='server_id',
        ),
        migrations.AddField(
            model_name='remotelog',
            name='command_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
